// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tz.applyjob.domain;

import com.tz.applyjob.domain.Applyjob;
import com.tz.applyjob.domain.ApplyjobDataOnDemand;
import com.tz.applyjob.domain.ApplyjobIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ApplyjobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ApplyjobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ApplyjobIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ApplyjobIntegrationTest: @Transactional;
    
    @Autowired
    ApplyjobDataOnDemand ApplyjobIntegrationTest.dod;
    
    @Test
    public void ApplyjobIntegrationTest.testCountApplyjobs() {
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", dod.getRandomApplyjob());
        long count = Applyjob.countApplyjobs();
        Assert.assertTrue("Counter for 'Applyjob' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ApplyjobIntegrationTest.testFindApplyjob() {
        Applyjob obj = dod.getRandomApplyjob();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to provide an identifier", id);
        obj = Applyjob.findApplyjob(id);
        Assert.assertNotNull("Find method for 'Applyjob' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Applyjob' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ApplyjobIntegrationTest.testFindAllApplyjobs() {
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", dod.getRandomApplyjob());
        long count = Applyjob.countApplyjobs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Applyjob', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Applyjob> result = Applyjob.findAllApplyjobs();
        Assert.assertNotNull("Find all method for 'Applyjob' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Applyjob' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ApplyjobIntegrationTest.testFindApplyjobEntries() {
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", dod.getRandomApplyjob());
        long count = Applyjob.countApplyjobs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Applyjob> result = Applyjob.findApplyjobEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Applyjob' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Applyjob' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ApplyjobIntegrationTest.testFlush() {
        Applyjob obj = dod.getRandomApplyjob();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to provide an identifier", id);
        obj = Applyjob.findApplyjob(id);
        Assert.assertNotNull("Find method for 'Applyjob' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApplyjob(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Applyjob' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplyjobIntegrationTest.testMergeUpdate() {
        Applyjob obj = dod.getRandomApplyjob();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to provide an identifier", id);
        obj = Applyjob.findApplyjob(id);
        boolean modified =  dod.modifyApplyjob(obj);
        Integer currentVersion = obj.getVersion();
        Applyjob merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Applyjob' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplyjobIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", dod.getRandomApplyjob());
        Applyjob obj = dod.getNewTransientApplyjob(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Applyjob' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Applyjob' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ApplyjobIntegrationTest.testRemove() {
        Applyjob obj = dod.getRandomApplyjob();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Applyjob' failed to provide an identifier", id);
        obj = Applyjob.findApplyjob(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Applyjob' with identifier '" + id + "'", Applyjob.findApplyjob(id));
    }
    
}
