// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tz.applyjob.domain;

import com.tz.applyjob.domain.ApplyjobIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplyjobIntegrationTest_Roo_Configurable {
    
    declare @type: ApplyjobIntegrationTest: @Configurable;
    
}
