// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tz.applyjob.domain;

import com.tz.applyjob.domain.ApplyjobDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplyjobDataOnDemand_Roo_Configurable {
    
    declare @type: ApplyjobDataOnDemand: @Configurable;
    
}
